version: '3.1'
# for development

services: 
    db:
        image: postgres:12-alpine
        volumes:
            - db_data:/var/lib/postgresql/data
        environment: 
            - POSTGRES_USER=contestbot
            - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
            - POSTGRES_INITDB_ARGS=--encoding=UTF-8
        secrets:
            - db_password
    contestbot:
        build:
            context: .
            dockerfile: ./Dockerfile-dev
        secrets:
            - db_password
        environment: 
            - BOT_DB_NAME=contestbot
            - BOT_DB_USERNAME=contestbot
            - BOT_DB_PASSWORD_FILE=/run/secrets/db_password
            - BOT_SLACK_TOKEN_FILE=/run/secrets/slack_token
        volumes:
            - ./:/app/
        secrets:
            - db_password
            - slack_token
        command: python app.py

secrets:
    db_password:
        file: ./secrets/db_password.txt
    slack_token:
        file: ./secrets/slack_token.txt

volumes:
    db_data: